name: Deploy to production environment

on:
  push:
    branches:
      - production

jobs:
  redeploy_everything:
    name: Redeploy everything to production
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/ssh_key
          ssh -i ~/ssh_key root@ip_address_of_production_server -t "cd monorepo-demo/ && git pull origin production && export PATH=/root/.nvm/versions/node/v22.13.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin && npm install -g pnpm && pnpm install && pnpm run build && pm2 restart web-server && pm2 restart http-server && pm2 restart ws-server"
